const { esc, config } = require('../lib');
const C = require('../components');

const crumbs = [{ name: 'Terms of Use', path: '/terms/' }];

const body = [
  C.pageHero({
    crumbs,
    eyebrow: 'Legal Terms',
    h1: 'Terms and Conditions',
    lead: 'General terms and conditions governing the informational use of the Ayodhya Solar Installation website.',
  }),
  `<section class="section"><div class="container"><div class="prose prose--narrow">
<p><strong>Last Updated:</strong> October 2026</p>
<p>Welcome to <strong>${esc(config.siteName)}</strong>. By accessing or using our website, you agree to comply with and be bound by the following terms of use.</p>

<h2>1. Informational Purpose</h2>
<p>The content, articles, estimation tools, and guides provided on this website are designed for general informational and educational guidance regarding residential and commercial rooftop solar photovoltaic systems in Ayodhya and Faizabad, Uttar Pradesh.</p>

<h2>2. No Binding Quotation from Website Tools</h2>
<p>Outputs generated by our online solar calculator, indicative cost tables, and general articles are rough mathematical approximations. They do not constitute a formal, binding commercial contract or legally enforceable guarantee of energy generation. A binding quotation is only provided after an in-person physical site survey and signed project agreement.</p>

<h2>3. Independent Commercial Business</h2>
<p><strong>${esc(config.siteName)}</strong> is an independent local solar installation business. We are not a government department, state utility, or official branch of MNRE, UPNEDA, or MVVNL. We assist eligible domestic customers with government subsidy filing as a commercial service provider, but all subsidy decisions and disbursement timelines rest solely with the Government of India and relevant state authorities.</p>

<h2>4. Intellectual Property</h2>
<p>The text content, visual diagrams, code scripts, and layout branding of this website are the intellectual property of ${esc(config.siteName)} unless otherwise specified. Reproduction or scraping without prior written consent is prohibited.</p>

<h2>5. Limitation of Liability</h2>
<p>In no event shall ${esc(config.siteName)} be liable for any indirect, incidental, or consequential damages resulting from reliance on the informational calculators, changing subsidy regulations, or external portal downtime.</p>

<h2>6. Governing Law</h2>
<p>These terms and any disputes arising out of the use of this website shall be governed by the laws of India, within the jurisdiction of courts in Ayodhya / Faizabad, Uttar Pradesh.</p>

<h2>7. Contact Information</h2>
<p>For any legal inquiries regarding these terms, contact us at <a href="mailto:${config.business.email}">${esc(config.business.email)}</a> or by telephone at ${esc(config.business.phoneDisplay)}.</p>
</div></div></section>`,
].join('\n');

module.exports = {
  path: '/terms/',
  title: 'Terms of Use | Ayodhya Solar Installation',
  description:
    'Terms and conditions of use for Ayodhya Solar Installation website. Informational scope, independent business status, and quotation guidelines.',
  hasForm: false,
  breadcrumbs: crumbs,
  sitemap: { priority: '0.3', changefreq: 'yearly' },
  body,
};
